- name: Deploy and execute script on all VPSs
  hosts: all
  become: yes
  tasks:

    - name: Copy script to VPS
      copy:
        src: /root/notify_backup_tele/script.sh
        dest: /orkitools/tele_backup.sh
        mode: '0755'

    - name: Execute script
      shell: /orkitools/tele_backup.sh

    - name: Add new cron job for tele_backup script
      lineinfile:
        path: /etc/cron.d/backup
        line: '40 23 * * * root /bin/bash /orkitools/tele_backup.sh'
        create: yes
        state: present
